# Generated by Django 3.1 on 2021-03-05 08:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_the_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_the_school', ckeditor.fields.RichTextField(blank=True)),
                ('S_Name', models.CharField(blank=True, max_length=150)),
                ('S_Motto', models.CharField(blank=True, max_length=150)),
                ('Total', models.CharField(blank=True, max_length=150)),
                ('Streams', models.CharField(blank=True, max_length=150)),
                ('Zone', models.CharField(blank=True, max_length=150)),
                ('County', models.CharField(blank=True, max_length=150)),
                ('Subcounty', models.CharField(blank=True, max_length=150)),
                ('Category', models.CharField(blank=True, max_length=150)),
                ('Sponsor', models.CharField(blank=True, max_length=150)),
                ('Address', models.CharField(blank=True, max_length=150)),
                ('Vision', models.CharField(blank=True, max_length=150)),
                ('Mission', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
