# Generated by Django 3.1 on 2021-03-05 08:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_1', models.CharField(blank=True, max_length=200)),
                ('Phone_2', models.CharField(blank=True, max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Twitter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('Instagram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('Facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('Other_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='background')),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-pk', 'Photo'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=100)),
                ('Teachers_photo', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('Teachers_name', models.CharField(max_length=100)),
                ('Teachers_first_subject', models.CharField(max_length=100)),
                ('Teachers_second_subject', models.CharField(max_length=100)),
                ('Employer', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Record_updated_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-Record_updated_on', 'Teachers_name'),
            },
        ),
    ]
