# Generated by Django 3.1 on 2021-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo1_Description', models.CharField(blank=True, max_length=50)),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo2_Description', models.CharField(blank=True, max_length=50)),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo3_Description', models.CharField(blank=True, max_length=50)),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo4_Description', models.CharField(blank=True, max_length=50)),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo5_Description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('-pk', 'photo1'),
            },
        ),
    ]
