# Generated by Django 3.1 on 2021-03-05 08:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scroll_text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
