# Generated by Django 3.1 on 2021-03-05 08:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(blank=True, default='Teacher', max_length=100, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('About', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Home_County', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=105, null=True)),
            ],
        ),
    ]
