# Generated by Django 3.1 on 2021-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='files')),
                ('File_Name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-pk', 'File_Name'),
            },
        ),
    ]
