# Generated by Django 3.1 on 2021-03-05 08:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('event_title', models.TextField(blank=True)),
                ('event_description', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ('-post_date', 'event_date'),
            },
        ),
    ]
