# Generated by Django 3.1 on 2021-03-05 08:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_department', models.CharField(max_length=100)),
                ('HOD', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject_3', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject_4', models.CharField(blank=True, max_length=10, null=True)),
                ('Subject_5', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject_6', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject_7', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_3', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_4', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_5', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_6', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_7', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_8', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_9', models.CharField(blank=True, max_length=100, null=True)),
                ('Assistant_10', models.CharField(blank=True, max_length=100, null=True)),
                ('About', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
