# Generated by Django 3.1 on 2021-03-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentsmodel',
            old_name='user',
            new_name='author',
        ),
    ]
